image: node:latest

# This folder is cached between builds
# https://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    # Enables git-lab CI caching. Both .cache and public must be cached, otherwise builds will fail.
    - .cache/
    - public/

pages:
  stage: build
  script:
    - yarn install
    - npm run clean
    # Pass --prefix-paths to gatsby build
    - npm run build -- --prefix-paths
  artifacts:
    paths:
      - public
  only:
    - main
