name: Lint (Check)

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm i prettier --no-scripts

      - name: Run prettier
        run: npx prettier -c .
