name: Mirror

# Dependabot PRs do not have the same access to secrets.
on:
  push:
    branches:
      - "**"
      - "!dependabot/**"
  # Will trigger on a merge commit (push) so deleted branches will be synced on the next push to any matching branch.
  delete:
    branches:
      - "**"
      - "!dependabot/**"

jobs:
  igem-gitlab:
    name: iGEM GitLab

    # If this job is running more than once on the same branch,
    # cancel the older job.
    # https://docs.github.com/en/actions/using-jobs/using-concurrency
    # UPDATE: Some runs such as https://github.com/genoswitch/wiki/actions/runs/5665169353/job/15349559463
    # are failing. Let's try to only use the workflow name as the concurrency group.
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # all branches and tags

      - name: Mirror repository
        uses: genoswitch/repository-mirroring-action@a76d61cd1d28ee9e2ab5b6b19cc825736f02b38d
        with:
          target_repo_url: git@gitlab.igem.org:2023/city-of-london-uk.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_KEY }}
